config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/preprocessor:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/preprocessor.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-pink-devil.sh
        container: qc.acc_skanky-gamboge-eel
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-green-anteater.sh
        container: qc.doc_queasy-cyan-dugong
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-olive-hedgehog.sh
        container: qc.doc_droopy-violet-sponge
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-charcoal-shark.sh
        container: qc.doc_skinny-sapphire-lion
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-eggplant-dragonfly.sh
        container: qc.lic_crappy-razzmatazz-terrier
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-maroon-ant.sh
        container: qc.sty_stinky-cobalt-hare
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-black-jackal.sh
        container: qc.sty_snoopy-cornflower-balinese
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-seashell-chinchilla.sh
        container: qc.sty_messy-cerise-gharial
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-malachite-bat.sh
        container: qc.ver_trippy-magenta-fly
timeout: 5400
